// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqierduvidlvcdxkpiba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaWVyZHV2aWRsdmNkeGtwaWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjk4ODQsImV4cCI6MjA2NjUwNTg4NH0.NghiWPNgzX6cj4_RQcZuznpO55DyGu8tWVp-ouuDJGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);